version: "3.8"
services:
  postgres_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Monkey92
      POSTGRES_DB: work_finder_api_db

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      db-server: postgres_db